### ISSUE TITLE
Error: <stdin>:1: syntax error near line 1

### ISSUE THREAD

**Issue by hcientist** [preston/railroady#41]
When I run `diagram:all`, and then even just

```
rake diagram:models:brief
```

I get an error:

```
rake diagram:models:brief
WARNING: Nokogiri was built against LibXML version 2.7.3, but has dynamically loaded 2.7.8
Generating /wherever/doc/models_brief.svg
railroady -bilamM | sed -E 's/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g' | dot -Tsvg > /wherever/doc/models_brief.svg
WARNING: Nokogiri was built against LibXML version 2.7.3, but has dynamically loaded 2.7.8
Error: <stdin>:1: syntax error near line 1
context:   >>>   (0.4ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" 
Warning: <stdin>:1: ambiguous "1m" splits into two names: "1" and "m"
Warning: <stdin>:1: ambiguous "36m" splits into two names: "36" and "m"
Warning: <stdin>:1: ambiguous "0.4ms" splits into two names: "0.4" and "ms"
Warning: <stdin>:1: ambiguous "0m" splits into two names: "0" and "m"
Warning: <stdin>:1: ambiguous "1mSELECT" splits into two names: "1" and "mSELECT"
Warning: <stdin>:1: ambiguous "0m" splits into two names: "0" and "m"
rake aborted!
Command failed with status (1): [railroady -bilamM | sed -E 's/\x1B\[([0-9]...]

Tasks: TOP => diagram:models:brief
(See full trace by running task with --trace)
```

so with trace, 

```
rake diagram:models:brief --trace
WARNING: Nokogiri was built against LibXML version 2.7.3, but has dynamically loaded 2.7.8
** Invoke diagram:models:brief (first_time)
** Execute diagram:models:brief
Generating /wherever/doc/models_brief.svg
railroady -bilamM | sed -E 's/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g' | dot -Tsvg > /wherever/doc/models_brief.svg
WARNING: Nokogiri was built against LibXML version 2.7.3, but has dynamically loaded 2.7.8
Error: <stdin>:1: syntax error near line 1
context:   >>>   (0.6ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" 
Warning: <stdin>:1: ambiguous "1m" splits into two names: "1" and "m"
Warning: <stdin>:1: ambiguous "36m" splits into two names: "36" and "m"
Warning: <stdin>:1: ambiguous "0.6ms" splits into two names: "0.6" and "ms"
Warning: <stdin>:1: ambiguous "0m" splits into two names: "0" and "m"
Warning: <stdin>:1: ambiguous "1mSELECT" splits into two names: "1" and "mSELECT"
Warning: <stdin>:1: ambiguous "0m" splits into two names: "0" and "m"
rake aborted!
Command failed with status (1): [railroady -bilamM | sed -E 's/\x1B\[([0-9]...]
/MYUSER/.rvm/gems/ruby-1.9.3-p125@global/gems/rake-0.9.2.2/lib/rake/file_utils.rb:53:in `block in create_shell_runner'
/MYUSER/.rvm/gems/ruby-1.9.3-p125@global/gems/rake-0.9.2.2/lib/rake/file_utils.rb:45:in `call'
/MYUSER/.rvm/gems/ruby-1.9.3-p125@global/gems/rake-0.9.2.2/lib/rake/file_utils.rb:45:in `sh'
/MYUSER/.rvm/gems/ruby-1.9.3-p125@global/gems/rake-0.9.2.2/lib/rake/file_utils_ext.rb:39:in `sh'
/MYUSER/.rvm/gems/ruby-1.9.3-p125@rails322Platypus/gems/railroady-1.1.0/tasks/railroady.rake:62:in `block (3 levels) in <top (required)>'
/MYUSER/.rvm/gems/ruby-1.9.3-p125@global/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `call'
/MYUSER/.rvm/gems/ruby-1.9.3-p125@global/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `block in execute'
/MYUSER/.rvm/gems/ruby-1.9.3-p125@global/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `each'
/MYUSER/.rvm/gems/ruby-1.9.3-p125@global/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'
/MYUSER/.rvm/gems/ruby-1.9.3-p125@global/gems/rake-0.9.2.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'
/MYUSER/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/MYUSER/.rvm/gems/ruby-1.9.3-p125@global/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/MYUSER/.rvm/gems/ruby-1.9.3-p125@global/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'
/MYUSER/.rvm/gems/ruby-1.9.3-p125@global/gems/rake-0.9.2.2/lib/rake/application.rb:116:in `invoke_task'
/MYUSER/.rvm/gems/ruby-1.9.3-p125@global/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block (2 levels) in top_level'
/MYUSER/.rvm/gems/ruby-1.9.3-p125@global/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `each'
/MYUSER/.rvm/gems/ruby-1.9.3-p125@global/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block in top_level'
/MYUSER/.rvm/gems/ruby-1.9.3-p125@global/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/MYUSER/.rvm/gems/ruby-1.9.3-p125@global/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'
/MYUSER/.rvm/gems/ruby-1.9.3-p125@global/gems/rake-0.9.2.2/lib/rake/application.rb:66:in `block in run'
/MYUSER/.rvm/gems/ruby-1.9.3-p125@global/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/MYUSER/.rvm/gems/ruby-1.9.3-p125@global/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'
/MYUSER/.rvm/gems/ruby-1.9.3-p125@global/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'
/MYUSER/.rvm/gems/ruby-1.9.3-p125@global/bin/rake:19:in `load'
/MYUSER/.rvm/gems/ruby-1.9.3-p125@global/bin/rake:19:in `<main>'
/MYUSER/.rvm/gems/ruby-1.9.3-p125@rails322Platypus/bin/ruby_noexec_wrapper:14:in `eval'
/MYUSER/.rvm/gems/ruby-1.9.3-p125@rails322Platypus/bin/ruby_noexec_wrapper:14:in `<main>'
Tasks: TOP => diagram:models:brief
```

Any suggestions? Thanks for your hard work on this.

**Comment by Erowlin** [comment]
Same problem here w/ ruby 2.0.0p481 , @evadne solution didn't work.

**Comment by daino3** [comment]
#olleolleolle :+1: 

for those running foreman this worked like a charm for me.

**Comment by benlieb** [comment]
I had a similar issue and found that the first part of the pipe sequence:

`railroady -lamM | sed -E 's/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g' | ...
`

this bit: 

`railroady -lamM
`

had extraneous input above what railroady was expecting would come out.

In my case I like to see SQL in my logs in dev and had this line in my development.rb:

`  ActiveRecord::Base.logger = Logger.new(STDOUT) #show queries in console
`

And that was logging some db queries into the roady output.

Using @evadne 's recommendation I put this in my development.rb and all is now well:


```

unless $0 =~ /(rake|railroady|erd)$/
  ActiveRecord::Base.logger = Logger.new(STDOUT) #show queries in console
end

```
