### ISSUE TITLE
Error when including concern in model

### ISSUE THREAD

**Issue by Olgagr** [preston/railroady#62]
I have a model Project which I includes concern:

```
class Project < ActiveRecord::Base
    include AuthorSettings
end
```

```
module AuthorSettings	
	extend ActiveSupport::Concern

	included do
		before_validation :set_up_author
	end

	def set_up_author
		self.created_by = 'Admin'
		self.updated_by = 'Admin'
	end

end
```

When I'm trying to invoke rake diagram:all I got an error:

```
** Invoke diagram:all (first_time)
** Invoke diagram:models:complete (first_time)
** Execute diagram:models:complete
Generating /Users/ograbek/Documents/my_projects/fpcalculator/doc/models_complete.svg
railroady -ilamM | sed -E 's/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g' | dot -Tsvg > /Users/ograbek/Documents/my_projects/fpcalculator/doc/models_complete.svg
sh: /Users/ograbek/Documents/my_projects/fpcalculator/doc/models_complete.svg: No such file or directory
Warning: exception Unable to autoload constant Concerns::AuthorSettings, expected /Users/ograbek/Documents/my_projects/fpcalculator/app/models/concerns/author_settings.rb to define it raised while trying to load model class app/models/concerns/author_settings.rb
rake aborted!
Command failed with status (1): [railroady -ilamM | sed -E 's/\x1B\[([0-9]{...]
/Users/ograbek/.rvm/gems/ruby-2.0.0-p247@fpcalculator/gems/rake-10.1.1/lib/rake/file_utils.rb:54:in `block in create_shell_runner'
/Users/ograbek/.rvm/gems/ruby-2.0.0-p247@fpcalculator/gems/rake-10.1.1/lib/rake/file_utils.rb:45:in `call'
/Users/ograbek/.rvm/gems/ruby-2.0.0-p247@fpcalculator/gems/rake-10.1.1/lib/rake/file_utils.rb:45:in `sh'
/Users/ograbek/.rvm/gems/ruby-2.0.0-p247@fpcalculator/gems/rake-10.1.1/lib/rake/file_utils_ext.rb:37:in `sh'
/Users/ograbek/.rvm/gems/ruby-2.0.0-p247@fpcalculator/gems/railroady-1.1.1/tasks/railroady.rake:55:in `block (3 levels) in <top (required)>'
/Users/ograbek/.rvm/gems/ruby-2.0.0-p247@fpcalculator/gems/rake-10.1.1/lib/rake/task.rb:236:in `call'
/Users/ograbek/.rvm/gems/ruby-2.0.0-p247@fpcalculator/gems/rake-10.1.1/lib/rake/task.rb:236:in `block in execute'
/Users/ograbek/.rvm/gems/ruby-2.0.0-p247@fpcalculator/gems/rake-10.1.1/lib/rake/task.rb:231:in `each'
/Users/ograbek/.rvm/gems/ruby-2.0.0-p247@fpcalculator/gems/rake-10.1.1/lib/rake/task.rb:231:in `execute'
/Users/ograbek/.rvm/gems/ruby-2.0.0-p247@fpcalculator/gems/rake-10.1.1/lib/rake/task.rb:175:in `block in invoke_with_call_chain'
/Users/ograbek/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/Users/ograbek/.rvm/gems/ruby-2.0.0-p247@fpcalculator/gems/rake-10.1.1/lib/rake/task.rb:168:in `invoke_with_call_chain'
/Users/ograbek/.rvm/gems/ruby-2.0.0-p247@fpcalculator/gems/rake-10.1.1/lib/rake/task.rb:197:in `block in invoke_prerequisites'
/Users/ograbek/.rvm/gems/ruby-2.0.0-p247@fpcalculator/gems/rake-10.1.1/lib/rake/task.rb:195:in `each'
/Users/ograbek/.rvm/gems/ruby-2.0.0-p247@fpcalculator/gems/rake-10.1.1/lib/rake/task.rb:195:in `invoke_prerequisites'
/Users/ograbek/.rvm/gems/ruby-2.0.0-p247@fpcalculator/gems/rake-10.1.1/lib/rake/task.rb:174:in `block in invoke_with_call_chain'
/Users/ograbek/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/Users/ograbek/.rvm/gems/ruby-2.0.0-p247@fpcalculator/gems/rake-10.1.1/lib/rake/task.rb:168:in `invoke_with_call_chain'
/Users/ograbek/.rvm/gems/ruby-2.0.0-p247@fpcalculator/gems/rake-10.1.1/lib/rake/task.rb:161:in `invoke'
/Users/ograbek/.rvm/gems/ruby-2.0.0-p247@fpcalculator/gems/rake-10.1.1/lib/rake/application.rb:149:in `invoke_task'
/Users/ograbek/.rvm/gems/ruby-2.0.0-p247@fpcalculator/gems/rake-10.1.1/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/ograbek/.rvm/gems/ruby-2.0.0-p247@fpcalculator/gems/rake-10.1.1/lib/rake/application.rb:106:in `each'
/Users/ograbek/.rvm/gems/ruby-2.0.0-p247@fpcalculator/gems/rake-10.1.1/lib/rake/application.rb:106:in `block in top_level'
/Users/ograbek/.rvm/gems/ruby-2.0.0-p247@fpcalculator/gems/rake-10.1.1/lib/rake/application.rb:115:in `run_with_threads'
/Users/ograbek/.rvm/gems/ruby-2.0.0-p247@fpcalculator/gems/rake-10.1.1/lib/rake/application.rb:100:in `top_level'
/Users/ograbek/.rvm/gems/ruby-2.0.0-p247@fpcalculator/gems/rake-10.1.1/lib/rake/application.rb:78:in `block in run'
/Users/ograbek/.rvm/gems/ruby-2.0.0-p247@fpcalculator/gems/rake-10.1.1/lib/rake/application.rb:165:in `standard_exception_handling'
/Users/ograbek/.rvm/gems/ruby-2.0.0-p247@fpcalculator/gems/rake-10.1.1/lib/rake/application.rb:75:in `run'
/Users/ograbek/.rvm/gems/ruby-2.0.0-p247@fpcalculator/gems/rake-10.1.1/bin/rake:33:in `<top (required)>'
/Users/ograbek/.rvm/gems/ruby-2.0.0-p247@fpcalculator/bin/rake:23:in `load'
/Users/ograbek/.rvm/gems/ruby-2.0.0-p247@fpcalculator/bin/rake:23:in `<main>'
/Users/ograbek/.rvm/gems/ruby-2.0.0-p247@fpcalculator/bin/ruby_executable_hooks:15:in `eval'
/Users/ograbek/.rvm/gems/ruby-2.0.0-p247@fpcalculator/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => diagram:all => diagram:models:complete
```

**Comment by jmaddi** [comment]
:+1:

**Comment by kimegede** [comment]
:+1:

**Comment by preston** [comment]
@volontarian If you wouldn't mind, could you please submit PR for this issue? I'm still not seeing it on my own projects but am happy to merge it in.

**Comment by volontarian** [comment]
@preston The pull request can be found here: https://github.com/preston/railroady/pull/99

**Comment by preston** [comment]
Done!

**Comment by preston** [comment]
Released in v1.4.1.

**Comment by ponysmith** [comment]
For reference, my app had an all uppercase module namespace, so even after the patch, the camelize wasn't working properly.  For example:

`/app/models/abc/some_model.rb` with module namespace `ABC` would still look for the module namespace `Abc`.  

This can be solved by adding an inflector:

    ActiveSupport::Inflector.inflections do |inflect|
        inflect.acronym 'ABC'
    end

**Comment by preston** [comment]
@ponysmith Ah yeah, that sounds like a general activesupport issue best handled by an Inflector. Thanks!
