### ISSUE TITLE
Generating AASM diagram fails

### ISSUE THREAD

**Issue by mknapik** [preston/railroady#75]
Model:
```ruby
class SomeModel < ActiveRecord::Base
  include AASM
end
```

Error:
```
$ bundle exec railroady --verbose -A
Loading application environment
Loading application classes as we go
Generating AASM diagram
    Processing SomeModel
        processing as acts_as_state_machine
~/.rvm/gems/ruby-2.1.1@gemset/gems/activerecord-4.1.6/lib/active_record/dynamic_matchers.rb:26:in `method_missing': undefined method `read_inheritable_attribute' for #<Class:0x007ff8eee795e8> (NoMethodError)
    from ~/.rvm/gems/ruby-2.1.1@gemset/gems/railroady-1.1.2/lib/railroady/aasm_diagram.rb:68:in `block in process_acts_as_state_machine_class'
    from ~/.rvm/gems/ruby-2.1.1@gemset/gems/railroady-1.1.2/lib/railroady/aasm_diagram.rb:67:in `each'
    from ~/.rvm/gems/ruby-2.1.1@gemset/gems/railroady-1.1.2/lib/railroady/aasm_diagram.rb:67:in `process_acts_as_state_machine_class'
    from ~/.rvm/gems/ruby-2.1.1@gemset/gems/railroady-1.1.2/lib/railroady/aasm_diagram.rb:58:in `process_class'
    from ~/.rvm/gems/ruby-2.1.1@gemset/gems/railroady-1.1.2/lib/railroady/aasm_diagram.rb:26:in `block in generate'
    from ~/.rvm/gems/ruby-2.1.1@gemset/gems/railroady-1.1.2/lib/railroady/aasm_diagram.rb:25:in `each'
    from ~/.rvm/gems/ruby-2.1.1@gemset/gems/railroady-1.1.2/lib/railroady/aasm_diagram.rb:25:in `generate'
    from ~/.rvm/gems/ruby-2.1.1@gemset/gems/railroady-1.1.2/bin/railroady:54:in `<top (required)>'
    from ~/.rvm/gems/ruby-2.1.1@gemset/bin/railroady:23:in `load'
    from ~/.rvm/gems/ruby-2.1.1@gemset/bin/railroady:23:in `<main>'
    from ~/.rvm/gems/ruby-2.1.1@gemset/bin/ruby_executable_hooks:15:in `eval'
    from ~/.rvm/gems/ruby-2.1.1@gemset/bin/ruby_executable_hooks:15:in `<main>'
```

Installed gems:
```
rails (4.1.6)
aasm (3.3.3)
railroady (1.1.2)
```

Any ideas how to fix it?

**Comment by indigoviolet** [comment]
Is this commit not merged?

**Comment by preston** [comment]
Not unless someone submitted a PR and can validate any specific AASM code. I'm happy to merge it in upstream and release an update.

**Comment by preston** [comment]
A patch for #111 was recently merged in. This may be worth trying again in v1.5.2.
