### ISSUE TITLE
get error Command failed with status (2) when run 'rake diagram:all'

### ISSUE THREAD

**Issue by karinelisabeth** [preston/railroady#88]
Hi, I have installed railroady, but I get the error: 'Command failed with status (2)' when run 'rake diagram:all'. I am using rails v4.2.0. It creates the /doc file without any problems.

Here is the full error message:

sh: -c: line 0: unexpected EOF while looking for matching `''
sh: -c: line 1: syntax error: unexpected end of file
rake aborted!
Command failed with status (2): [railroady -lamM | sed -E 's/\x1B\[([0-9]{1...]

**Comment by preston** [comment]
That's odd. What's the full output?

**Comment by karinelisabeth** [comment]
Thanks for quick reply! Here is the full output:

$ rake diagram:all --trace
** Invoke diagram:all (first_time)
** Invoke diagram:setup:create_new_doc_folder_if_needed (first_time)
** Execute diagram:setup:create_new_doc_folder_if_needed
** Invoke diagram:models:complete (first_time)
** Execute diagram:models:complete
Generating /Users/em/Documents/Eli's\ folder/ruby\ &\ rails/1\ -\ ruby\ &\ rails/3\ -\ rails\ to\ do\ application/ToDo_App/doc/models_complete.svg
railroady -lamM | sed -E 's/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g' | dot -Tsvg > /Users/em/Documents/Eli's\ folder/ruby\ &\ rails/1\ -\ ruby\ &\ rails/3\ -\ rails\ to\ do\ application/ToDo_App/doc/models_complete.svg
sh: -c: line 0: unexpected EOF while looking for matching `''
sh: -c: line 1: syntax error: unexpected end of file
rake aborted!
Command failed with status (2): [railroady -lamM | sed -E 's/\x1B\[([0-9]{1...]
/Users/em/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/file_utils.rb:66:in `block in create_shell_runner'
/Users/em/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/file_utils.rb:57:in `call'
/Users/em/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/file_utils.rb:57:in `sh'
/Users/em/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/file_utils_ext.rb:37:in `sh'
/Users/em/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railroady-1.3.0/tasks/railroady.rake:65:in `block (3 levels) in <top (required)>'
/Users/em/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/Users/em/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/Users/em/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/Users/em/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/Users/em/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/em/.rbenv/versions/2.1.5/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/Users/em/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Users/em/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:201:in `block in invoke_prerequisites'
/Users/em/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:199:in `each'
/Users/em/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:199:in `invoke_prerequisites'
/Users/em/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
/Users/em/.rbenv/versions/2.1.5/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/Users/em/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Users/em/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/Users/em/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/Users/em/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/em/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/Users/em/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/Users/em/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/Users/em/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/Users/em/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/Users/em/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/Users/em/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/Users/em/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/Users/em/.rbenv/versions/2.1.5/bin/rake:23:in `load'
/Users/em/.rbenv/versions/2.1.5/bin/rake:23:in `<main>'
Tasks: TOP => diagram:all => diagram:models:complete

**Comment by preston** [comment]
Hmm ... Windows I kindof a mystery to me so I'm not sure about this one, sorry!

**Comment by lingyan1002** [comment]
Excuse me, I encountered a problem when I ran "rake diagram:all", I found that the directory of my project is not consistent with the default directory, how can I solve this problem?

**Comment by preston** [comment]
I think you have a different issue than the OP, and I would suggest going to a more consistent structure. Other than being a good convention in general, Railroady does expect a standard directory structure.

**Comment by lingyan1002** [comment]
Is there any other solution? because my project is made up of many different modules and it is not suitable to revise the directory

**Comment by preston** [comment]
Most likely you'd have to fork and make some code changes. You could trying using symlinks, but I'm not sure that'll work.
